### ISSUE TITLE
NRIC may not be suitable field for foreigners

### ISSUE THREAD

**Issue by limrik** [AY2324S2-CS2103T-F10-3/tp#104]
As NRIC is only applicable to Singapore Citizens and PRs, clinic staff may face difficulties when faced with foreign patients

**Comment by xuelinglow** [comment]
I did a bit of searching and I found that passport numbers are generally also 9 characters? so maybe we can loosen the restrictions for nric so that we can use it for passport numbers for foreigners as well

**Comment by dayn-1** [comment]
Let's scope down to a Singaporean context, else we cannot ensure full compatibility with all passports and identifiers. We can caveat in the UG that filler NRICs can be used for foreign visitors, eg. "K0000001A", since these foreigners should not be staying long-term anyway - else they will be issued a FIN or equivalent.
